#ifndef FUNCTIONS_H
#define FUNCTIONS_H

s32  abs(s32 arg0);
s32  rand(void);
s8  *memset(s8 *s, s8 c, s32 len);
void memclr(s32 *src, s32 cnt);
s32 SquareRoot0(s32); /* extern */

// implicitly generated by gcc
f64 __adddf3(f64, f64);
f64 __floatsidf(s32);
f64 __muldf3(f64, f64);

// esa functions

void recharge_skill(s16);

void func_8006309C(u8 arg0, struct005 *animal);
void load_animal(s16 id);
void func_80076D60(s8 arg0);
void func_80076D94(void);
s32  create_particle_effect(s32 x, s32 z, s32 y, s16 id, s32, s32, s32, s32, u16 color1, u16 color2, s32); // TBD
void func_800A3630(void);
s32  func_800ABBB0(s32, s32, s32);

void func_800169CC(s16 numVtxs, void*, void*, s32);

// TODO:
// void func_8001B714(struct004 *arg0, u32 arg1, s32 arg2, void *arg3, s32 arg4, s16 arg5, s16 arg6, s16 arg7);
void func_8001B3FC(void);

// it's only called with 3 arg?!?
// s32 play_sound_effect_at_location(s32 id, s32 xPos, s32 zPos, s16 vol);
u16  func_8001CEB4(void);
s16  func_8001CED4(s16 idx);
s16  func_8001CF24(s16 arg0);
s8   func_8001CF7C(u8 idx);
s16  func_8001CF98(s16 arg0);
s16  func_8001CFEC(s16 arg0, s16 arg1);
s16  func_8001D294(s32 arg0, s32 arg1, s32 arg2, s32 arg3);
s16  func_8001EA40(s16 arg0, s16 arg1, s32 arg2, s8 arg3, s8 arg4, s32 arg5, s32 arg6, u8 arg7);
void func_8001EE3C(s8);
void func_8001F180(void);

void func_8002E6A0(s32);

s32  func_80030364(Animal *);

s32  func_80037098(s16 x, s16 z, u8 arg2);
s32  func_800370FC(s32, s32);
s32  func_800373B0(s16, s16);

void func_8003961C(void *buf, s32 offset, s32 length, s32 value);
s32  func_800397B0(s16 arg0, s16 arg1, s32 arg2, Animal *arg3, s32 arg4, Animal **arg5, s32 *arg6, s32 arg7, Animal **arg8, s32 *arg9);
void func_8003AF20(void);
void func_8003AEF0(s16, s8);
void func_8003E5EC(void);

s32  func_8004596C(void);
struct000 *func_80047108(Animal *arg0, s16 arg1, u16 arg2);
void func_8004F828(struct004 *arg0, s16 arg1, s16 arg2, s16 arg3, s16 arg4);
void func_80046850(struct004* arg0);
Object *func_8004D1B8(void);
void func_8004D86C(Object *);

s32  func_800509BC(u8 arg0, f32 arg1, f32 arg2, f32 arg3, f32 arg4);
void func_80051544(Object *arg0);
void func_80051A94(Object *arg0);
void func_80051CD0(Object *arg0);
void func_8005F8F8(void);

void *spawn_animal(s16 arg0, s16 arg1, s16 arg2, s16 rotation, s16 health, s16 id, s8 arg6);

void func_80061670(struct000 *arg0);
void func_80061688(struct000 *arg0, struct000 *arg1, u16 arg2);
void func_80061700(Animal *arg0, s16 arg1);
void func_8006173C(struct000 *arg0, struct000 *arg1);
void func_80061764(struct000 *arg0, void *arg1, s16 arg2);
void func_8006179C(struct000 *arg0);
void func_80061AF0(struct000 *arg0, s16 arg1, s16 arg2, s16 arg3, s8 arg4, u8 arg5);
void func_80061B68(struct000 *arg0);
void func_80061C60(struct000 *arg0, struct000 *arg1, s16 arg2, s16 arg3);
void func_80061D44(struct000 *arg0, struct000 *arg1);
void func_80061E74(Animal *arg0, u16 arg1, s16 arg2, s16 arg3);

void func_80062F98(s16 *arg0, s16 arg1, u16 arg2);
void func_8006303C(s16 *arg0, s16 arg1, u16 arg2);
s32  func_80064DC4(u16 arg0);

void func_8006B88C(s16, s32, s32, struct021 *, u8, u8, u8);
void func_8006BC30(s16 arg0, s16 arg1, s16 arg2, s16 arg3, void *img, s16 arg5, s16 arg6, s16 alpha, s16 red, s16 green, s16 blue, s16 argB, u8 argC);
void func_8006C6E8(s16 *arg0, s16 arg1, s16 arg2, s16 arg3, s16 arg4, s16 arg5, s16 arg6);
void func_8006FC24(s16 numVtxs, struct021 *vtxs, s16 arg3, s16 arg4, u8 arg6, u8 arg7, s16 red, s16 green, s16 blue, s32 argB, s32 argC, s32 argD, s32 argE);
void func_80070190(s16 numVtxs, struct021 *vtxs, s32 arg2, s16 arg3, s16 arg4, s32 arg5, s16 arg6, s16 arg7, s16 arg8, s32 arg9, s32 argA, s32 argB, s32 argC);
void func_8007080C(s16 arg0, void *arg1, s16 arg2, s16 arg4, s16 arg5, s16 arg6, s16 arg7); // ?

void func_800775B8(void);
void func_80078550(void);
void func_8007C444(struct000 *);
struct003 *func_80077CD8(void);
void func_8007F278(void);
void func_8007DFC4(u16);
void func_8007DA18(struct000*, s16);
s32  func_80082D94(s16 arg0, s16 arg1, s16 arg2, s16 arg3, s16 arg4, s16 arg5, s16 arg6, u8 arg7);
void func_800849B8(s32 arg0);

void func_80082294(s32, s32, s32);

// camel
void func_800999CC(void);
void func_80099C2C(u16 arg0);

void func_800A0720(s32 arg0, ...);
void func_800A0ADC(void);
void func_800A0F8C(void);
void func_800A1294(void);
void func_800A186C(u16 arg0);
s32  func_800A22B0(u16 arg0, s16 arg1); // or definition is missing from overlay2_76E7D0
void func_800A2344(s32);
void func_800A3A38(s32);

// TBD
// void func_800A2698(s32 arg0, s16 arg1, s16 arg2, s16 arg3, s16 arg4);
void func_800A350C(s32); // tbd
void func_800B0780(s32);
void func_800B0994(s32, s16*);
void func_800B39F4(struct013 *arg0, struct013 *arg1);
void func_800B3A20(struct013 *arg0);
s32  func_800B628C(s32);
void func_800B63A8(s16*);
void func_800BA7BC(s32);
void func_800C1DD4(s32*, s32*);

void func_800C1148(s32, s16);
s32  func_800C1F00(s32 arg0, s32 arg1);

#endif
