name: Create and push Docker build image
on:
  push:
    branches: [ master ]
    paths:
      - Dockerfile
      - packages.txt
      - requirements.txt
      - .bash_aliases
      - .github/workflows/docker.yaml
jobs:
  push_to_dockerhub:
    name: Build image and push to Github Registry
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push to Github registry
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ghcr.io/${{ github.repository }}:latest
